export const SAVE_STORE = "SAVE_STORE";
export const SAVE_SETTLEMENT = "SAVE_SETTLEMENT";
export const SAVE_PRODUCTS = "SAVE_PRODUCTS";
export const SAVE_CART = "SAVE_CART";
export const SAVE_CART_META = "SAVE_CART_META";
export const SAVE_STORE_NAME = "SAVE_STORE_NAME";
export const SAVE_STORE_INFO = "SAVE_STORE_INFO";
export const COMPLETED_ORDER_INFO = "COMPLETED_ORDER_INFO";
